Taskfile verbeterd en eerste versie startersgids

diff --git a/TaskFile.yml b/TaskFile.yml
--- a/TaskFile.yml
+++ b/TaskFile.yml
@@ -225,6 +225,15 @@ tasks:
       - echo 'Deploying to GitHub Pages...'
       - git push origin gh-pages
 
+
+  publish-test:
+    desc: "Publish the documentation to test location on host {{.FTP_HOST}}"
+    deps: [deploy-docs]
+    cmds:
+      - echo 'Deploying to test location...'
+      - lftp -e "set ssl:verify-certificate no; cd {{.FTP_REMOTE_DIR}}; mirror -R --delete --verbose ./{{.FTP_LOCAL_DIR}} .; bye" {{.FTP_HOST}}
+    shell: bash  
+
   full-deploy:
     desc: "Execute the entire deployment process."
     cmds:
@@ -252,3 +261,38 @@ tasks:
       - crunch_uml -sch "{{.GGM_ROOT_SCHEMA}}" export -f "{{.GGM}}" -t earepo --tag_strategy upsert
       - echo "Data successfully loaded into repository..."
     shell: bash
+  
+  util-generate-i18n:
+    desc: "Genereer vertalingen voor alle talen opgegeven in de .env variabele LANGUAGES. Output naar '{{.i18N_FILE}}'"
+    deps: [import-xmi]
+    cmds:
+      - |
+        if [ -z "{{.LANGUAGES}}" ]; then
+          echo "Error: LANGUAGES is niet ingesteld in .env."
+          exit 1
+        fi
+
+        echo "Reading GGM Datamodel {{.XMI}}..."
+        # crunch_uml import -f "{{.XMI}}" -t eaxmi -db_create
+
+        for LANG in $(echo "{{.LANGUAGES}}" | tr ',' ' '); do
+          for LANG in "${LANG_ARRAY[@]}"; do
+            LANG=$(echo "$LANG" | xargs)  # trim spaties
+            echo "Translating GGM to language $LANG..."
+            crunch_uml -sch "{{.GGM_ROOT_SCHEMA}}" export -t i18n -f "{{.i18N_FILE}}" --language "$LANG" --translate True --from_language "nl"
+
+            if [ $? -eq 0 ]; then
+              echo "Translation for language $LANG completed successfully."
+            else
+              echo "Error: Translation for language $LANG failed."
+              exit 1
+            fi
+          done
+        done
+    env:
+      LANGUAGES: "{{.LANGUAGES}}"
+    sources:
+      - "{{.XMI}}"
+    generates:
+      - "{{.i18N_FILE}}"
+    shell: bash  # <-- essentieel!
